### ISSUE TITLE
Having issue add panel with sankey-panel

### ISSUE THREAD

**Issue by talbaror** [kumaravel29/grafana-sankey-panel#10]
Hi,
When i am trying to use the plugin , i get following error below , the plugin is under 
/usr/share/grafana/public/app/plugins/panel/sankey-panel

Please adice
Thanks

```
Plugin Error
Fetch error: 404 Not Found Instantiating http://192.168.1.150:3000/public/app/plugins/panel/sankey-panel/module Loading app/plugins/panel/sankey-panel/module
```

**Comment by int2001** [comment]
Same here. Whereever i try to install it.

**Comment by kumaravel29** [comment]
@talbaror and @int2001 have you mentioned the directory of sankey-panel plugin in grafana.ini
https://github.com/kumaravel29/sankey-panel#clone-into-a-directory-of-your-choice

**Comment by talbaror** [comment]
> 
> 
> @talbaror and @int2001 have you mentioned the directory of sankey-panel plugin in grafana.ini
> https://github.com/kumaravel29/sankey-panel#clone-into-a-directory-of-your-choice

Hi
yes i did and restart grafana same result
Thanks
