### ISSUE TITLE
Compatibilty with Grafana 6

### ISSUE THREAD

**Issue by aflorezparra** [kumaravel29/grafana-sankey-panel#11]
Nice plugin! Is it compatible with Grafana 6? If not, what would be necessary to integrate it? Thanks!

**Comment by eNTy** [comment]
> Nice plugin! Is it compatible with Grafana 6? If not, what would be necessary to integrate it? Thanks!

+1. We use Grafana 6 as well. Unfortunately, this great plugin broke when we upgraded

**Comment by kumaravel29** [comment]
Will try updating it for Grafana 6 as well !

**Comment by bhozar** [comment]
Any progress on 6.x compatibility?

**Comment by kumaravel29** [comment]
@aflorezparra  and @bhozar I have updated the plugin. Please check if it works now.

**Comment by bhozar** [comment]
Unless I am missing something, it isn't working. I did git clone to the plugins folder. It gave me the following files:
![image](https://user-images.githubusercontent.com/1184220/71837628-cbceec80-30ae-11ea-96c7-7c27bdf84103.png)

After restarting Grafana I then had the following error:
![image](https://user-images.githubusercontent.com/1184220/71837588-b659c280-30ae-11ea-8aa3-cb5ca0be3bce.png)

**Comment by kumaravel29** [comment]
I have added the compiled dist folder.
Please test.

**Comment by bhozar** [comment]
Brilliant, thanks. It is now working.

**Comment by UL-he** [comment]
Hello,
It is the first time for me to install an external plugin in Grafana. 
With version 6.7.1 in a Docker Image I get the following error message after installing the sankey-panel "Error loading plugin if this plugin is loaded from git, make sure it was compiled. 
At the moment I missed the Step" Include loader.js in index.html "Is that why? If so, where can I usually find the Index.html file? 
Any Idea?

**Comment by UL-he** [comment]
fixed after include loader.js in "/usr/share/grafana/public/views/index.html"
