### ISSUE TITLE
Plugin fails to load on Grafana 6.4.4 and 6.7.2

### ISSUE THREAD

**Issue by pspangler** [kumaravel29/grafana-sankey-panel#21]
When attempting to install the sankey panel in Grafana I get an error message in the Grafana visualization panel "Error loading: grafana-sankey-panel"

* I tried installing this in the same place as other Grafana plugins (/var/lib/grafana/plugins)
* The thumbnail for the sankey visualization plugin does appear in the Grafana visualization gallery options.
* Nothing particularly helpful in the grafana log

t=2020-04-29T23:40:10+0000 lvl=info msg="Registering plugin" logger=plugins name="Sankey Diagram Chart"

Tried this on a couple of Linux instances in fact (tried this on CentOS 7.6 and AMZN AMI)

Any ideas?

**Comment by kumaravel29** [comment]
@pspangler Did you also load the loader.js as given in the Info section.
 
> In this plugin, the Sankey daigram panel has been used to visualize the distribution between 2 keys. Important - This panel is dependent on the google chart and requires loader.js which needs to be included in the Grafana index.html file
> 
> <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

**Comment by pspangler** [comment]
Oh, okay.  So basically I need to compile the grafana-server from source in
order to make that change, right?  I just installed Grafana from a standard
package so I don't think I can set up the sankey panel plugin from that, it
sounds like.

Thanks for pointing that line out on the plugin page in the Info section.

Peter

**Comment by kumaravel29** [comment]
@pspangler compilation should not be required as it is adding a line in the index.html file.
