### ISSUE TITLE
Does it support grafana 7 ?

### ISSUE THREAD

**Issue by aleita** [kumaravel29/grafana-sankey-panel#23]
Error Loading Plugin
Check the server startup logs for more information. 
If this plugin was loaded from git, make sure it was compiled.

**Comment by kumaravel29** [comment]
@aleita I am working on it and will release newer version support

**Comment by generb** [comment]
Same issue here. Would be awesome if this could be fixed.

**Comment by DislayPS** [comment]
I have the same issue running on Grafana 6.5.1 using sankey-panel version 3.0.0, please let us know if there's a fix

**Comment by kumaravel29** [comment]
I tested the plugin and seems to work fine with Grafana 7. 
Although I found a bug in terms of creating a new sankey panel. As known, it is required to specify 2 terms grouping to display the diagram, but I found that while creating a new panel and selecting the first term, the panel throws an exception.
The workaround in this can be done by first adding the 2 group by term options(as shown in screenshot) and then selecting the actual fields.
I will raise a bug and try fixing this.

![image](https://user-images.githubusercontent.com/6417038/87877353-23470100-c9de-11ea-8e69-6798516cd8d9.png)


@aleita can you please check if the index.html is being updated with the google charts link https://github.com/kumaravel29/grafana-sankey-panel#info

@DislayPS can you share the exact issue that you are facing?

**Comment by aleita** [comment]
Hi @kumaravel29 

it works for me.

<img width="747" alt="Screenshot 2020-07-20 at 10 22 19" src="https://user-images.githubusercontent.com/6066940/87915853-f55fcc00-ca72-11ea-93d1-746adc4894c0.png">


thanks

Ale

**Comment by DislayPS** [comment]
> I tested the plugin and seems to work fine with Grafana 7.
> Although I found a bug in terms of creating a new sankey panel. As known, it is required to specify 2 terms grouping to display the diagram, but I found that while creating a new panel and selecting the first term, the panel throws an exception.
> The workaround in this can be done by first adding the 2 group by term options(as shown in screenshot) and then selecting the actual fields.
> I will raise a bug and try fixing this.
> 
> ![image](https://user-images.githubusercontent.com/6417038/87877353-23470100-c9de-11ea-8e69-6798516cd8d9.png)
> 
> @aleita can you please check if the index.html is being updated with the google charts link https://github.com/kumaravel29/grafana-sankey-panel#info
> 
> @DislayPS can you share the exact issue that you are facing?

Hey @kumaravel29,

Thanks for the quick reply!

I am using Grafana version 6.5.1 and it shows the same error:
Error Loading Plugin
Check the server startup logs for more information.
If this plugin was loaded from git, make sure it was compiled.

Here's my screenshot:
<img width="1232" alt="Screen Shot 2020-07-20 at 9 00 35 AM" src="https://user-images.githubusercontent.com/42358911/87960191-ccd2d480-ca68-11ea-870f-90afa9acec8d.png">

Thanks for helping!

**Comment by kumaravel29** [comment]
@DislayPS, I tested the plugin with version 6.5.1 and it works fine.
Can you please share the steps involved in installing the plugin?

**Comment by DislayPS** [comment]
@kumaravel29 I installed grafana 6.5.1 with brew
Setup my custom repo inside grafana's config
I git clone https://github.com/kumaravel29/grafana-sankey-panel.git into my custom repo

I restart my grafana platform: brew services restart grafana
The plugin shows up so everything is fine so far.
I go on Configuration and Plugins, click on the new sankey plugin and it shows that screenshot above.

**Comment by kumaravel29** [comment]
@DislayPS Can you also share the Grafana logs.

**Comment by DislayPS** [comment]
@kumaravel29 thanks for helping,

I've attached the logs from Starting the grafana server, to going to Configuration - Plugins - Clicking on Sankey and getting the error from screenshot above.
Then also, trying to create a new dashboard with the sankey and getting the error on the screenshot below
<img width="1242" alt="Screen Shot 2020-07-20 at 12 49 17 PM" src="https://user-images.githubusercontent.com/42358911/87979876-93f62800-ca87-11ea-9a0b-e889313bdc31.png">


`t=2020-07-20T12:43:29-0700 lvl=info msg="Starting Grafana" logger=server version=6.5.1 commit=unknown-dev branch=master compiled=2020-07-20T11:56:06-0700
t=2020-07-20T12:43:29-0700 lvl=info msg="Config loaded from" logger=settings file=/usr/local/opt/grafana/share/grafana/conf/defaults.ini
t=2020-07-20T12:43:29-0700 lvl=info msg="Config loaded from" logger=settings file=/usr/local/etc/grafana/grafana.ini
t=2020-07-20T12:43:29-0700 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/usr/local/var/lib/grafana"
t=2020-07-20T12:43:29-0700 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/usr/local/var/log/grafana"
t=2020-07-20T12:43:29-0700 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/usr/local/var/lib/grafana/plugins"
t=2020-07-20T12:43:29-0700 lvl=info msg="Path Home" logger=settings path=/usr/local/opt/grafana/share/grafana
t=2020-07-20T12:43:29-0700 lvl=info msg="Path Data" logger=settings path=/usr/local/var/lib/grafana
t=2020-07-20T12:43:29-0700 lvl=info msg="Path Logs" logger=settings path=/usr/local/var/log/grafana
t=2020-07-20T12:43:29-0700 lvl=info msg="Path Plugins" logger=settings path=/Users/dtaing/Documents/work/grafana/plugins
t=2020-07-20T12:43:29-0700 lvl=info msg="Path Provisioning" logger=settings path=/usr/local/opt/grafana/share/grafana/conf/provisioning
t=2020-07-20T12:43:29-0700 lvl=info msg="App mode production" logger=settings
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing SqlStore" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-07-20T12:43:29-0700 lvl=info msg="Starting DB migration" logger=migrator
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing HTTPServer" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing OSSLicensingService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing SearchService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing RemoteCache" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing QuotaService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing ServerLockService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing UserAuthTokenService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing PluginManager" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Starting plugin search" logger=plugins
t=2020-07-20T12:43:29-0700 lvl=info msg="Registering plugin" logger=plugins name="Flowmaster Datasource"
t=2020-07-20T12:43:29-0700 lvl=info msg="Registering plugin" logger=plugins name="Pie Chart"
t=2020-07-20T12:43:29-0700 lvl=info msg="Registering plugin" logger=plugins name="Sankey Diagram Chart"
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing RenderingService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing AlertEngine" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing DatasourceCacheService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing HooksService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing LoginService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing InternalMetricsService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing TracingService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing UsageStatsService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing CleanUpService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing NotificationService" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing provisioningServiceImpl" logger=server
t=2020-07-20T12:43:29-0700 lvl=info msg="Backend rendering via phantomJS" logger=rendering
t=2020-07-20T12:43:29-0700 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin." logger=rendering
t=2020-07-20T12:43:29-0700 lvl=info msg="Initializing Stream Manager"
t=2020-07-20T12:43:29-0700 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-07-20T12:46:30-0700 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/ status=502 remote_addr=[::1] time_ms=11 size=0 referer=http://localhost:3000/datasources/edit/1/
t=2020-07-20T12:48:26-0700 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1/query status=400 remote_addr=[::1] time_ms=61 size=249 referer="http://localhost:3000/dashboard/new?panelId=2&edit&fullscreen&tab=visualization&openVizPicker&orgId=1"
t=2020-07-20T12:48:28-0700 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1/query status=400 remote_addr=[::1] time_ms=18 size=249 referer="http://localhost:3000/dashboard/new?panelId=2&edit&fullscreen&tab=visualization&openVizPicker&orgId=1"`

**Comment by kumaravel29** [comment]
@DislayPS I faced the same issue in Windows but things worked fine in my Ubuntu VM by cloning the sankey plugin. Could not find the details about the error for now.
Is it possible to use the grafana-cli to install the plugin and check if that works?

**Comment by DislayPS** [comment]
Hey @kumaravel29,

Just tried that, still the same result, I removed my old one, restarted the server and confirmed the plugin was not there anymore.
Then I ran these commands:
`us8c8590a73a04:plugins dtaing$ grafana-cli --pluginsDir "/Users/dtaing/Documents/work/grafana/plugins" --pluginUrl https://codeload.github.com/kumaravel29/grafana-sankey-panel/zip/master plugins install grafana-sankey-panel
installing grafana-sankey-panel @ 
from: https://codeload.github.com/kumaravel29/grafana-sankey-panel/zip/master
into: /Users/dtaing/Documents/work/grafana/plugins

✔ Installed grafana-sankey-panel successfully 

Restart grafana after installing plugins . <service grafana-server restart>

us8c8590a73a04:plugins dtaing$ brew services restart grafana
Stopping `grafana`... (might take a while)
==> Successfully stopped `grafana` (label: homebrew.mxcl.grafana)
==> Successfully started `grafana` (label: homebrew.mxcl.grafana)`

Still the same outcome =(

**Comment by b4b857f6ee** [comment]
> @aleita I am working on it and will release newer version support

Hello, nice plugin! Any ETA? :)

![image](https://user-images.githubusercontent.com/36012515/97846164-e7664c00-1ced-11eb-8cca-21c909a8cfce.png)

**Comment by kumaravel29** [comment]
@aleita the plugin works with v7.x also. Could you please let me know the steps done for the installation ?

**Comment by b4b857f6ee** [comment]
For me, i have just doe :
git clone https://github.com/kumaravel29/sankey-panel.git
sudo service grafana-server restart
And move it into my other location where is have all my plugin
![image](https://user-images.githubusercontent.com/36012515/97850646-9d349900-1cf4-11eb-8675-dc99a94bc20a.png)

**Comment by kumaravel29** [comment]
@aleita did you restart grafana after placing the plugin in the plugin folder?

Otherwise can you also try this command (enter the plugin directory)
grafana-cli --pluginUrl "https://github.com/kumaravel29/grafana-sankey-panel/archive/master.zip" --pluginsDir "${GF_PATHS_PLUGINS}" plugins install grafana-sankey-panel

**Comment by b4b857f6ee** [comment]
I still got the same, what can i do to show your more information?
![image](https://user-images.githubusercontent.com/36012515/97880856-f4049780-1d21-11eb-97a7-45ab733f32c4.png)

**Comment by b4b857f6ee** [comment]
No error 👍 Thank you i will try to do my grafphics
