### ISSUE TITLE
What should the data format look like?

### ISSUE THREAD

**Issue by h200920091** [kumaravel29/grafana-sankey-panel#34]
I'm trying this panel recently, and I finally install it successfully. But I faced a problem that the graph did not show after I finished setting.
![image](https://user-images.githubusercontent.com/49750831/114688179-0c53f600-9d47-11eb-8630-ec00989edf0f.png)

I wonder if it is the problem of my data format.
Here is what my data look like.
![image](https://user-images.githubusercontent.com/49750831/114688845-b0d63800-9d47-11eb-9813-0c77ae16db17.png)

Thanks.

**Comment by kumaravel29** [comment]
@h200920091 , one of the things I observe is that the legend shows "current" field. Do you receive data real time? or you can try selecting the "total" option in the legend and check

**Comment by h200920091** [comment]
Thanks!! After I select the "total" option, the graph does show.
