### ISSUE TITLE
any update for grafana v8

### ISSUE THREAD

**Issue by xsharepoint** [kumaravel29/grafana-sankey-panel#42]
can you update for grafana v8 bro ? if you can i will pay ^_^

**Comment by kumaravel29** [comment]
Planned it for this weekend, will update once tested.

**Comment by xsharepoint** [comment]
oke bro thanks  for that

**Comment by xsharepoint** [comment]
no update bro

**Comment by tilmaehn** [comment]
Can't wait for the plugin to work with Grafana 8 🤩

**Comment by kumaravel29** [comment]
Hi @xsharepoint and @tilmaehn
The plugin seems to work with Grafana v8.0.6 (68fe9e3431) but requires additional setting as unsigned plugins are disabled by default.
Unsigned plugins can be still used by additional environment variable GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-sankey-panel

Please let me know if you still face problem

**Comment by mentaripagiku** [comment]
> Hi @xsharepoint and @tilmaehn
> The plugin seems to work with Grafana v8.0.6 (68fe9e3431) but requires additional setting as unsigned plugins are disabled by default.
> Unsigned plugins can be still used by additional environment variable GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-sankey-panel
> 
> Please let me know if you still face problem

Still not showing sankey graph. 
Is there any other setting besides the env variables?

**Comment by kumaravel29** [comment]
@mentaripagiku can check or share the start up logs. If disabled, it should mention it there.
Also how are you installing the plugin? Can you share the steps?

**Comment by mentaripagiku** [comment]
- Running this command `grafana-cli --pluginUrl https://codeload.github.com/kumaravel29/grafana-sankey-panel/zip/master plugins install grafana-sankey-panel`
- Added GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-sankey-panel  below plugin section in /etc/grafana/grafana.ini
- restarted grafana server services.
Still not working and here is the log:
`t=2021-07-30T13:27:35+0700 lvl=info msg="Registering plugin" logger=plugins id=input
t=2021-07-30T13:27:35+0700 lvl=info msg="Registering plugin" logger=plugins id=grafana-plugin-admin-app
t=2021-07-30T13:27:35+0700 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=grafana-sankey-panel pluginDir=/var/lib/grafana/plugins/grafana-sankey-panel/dist
t=2021-07-30T13:27:35+0700 lvl=info msg="Registering plugin" logger=plugins id=grafana-sankey-panel
t=2021-07-30T13:27:35+0700 lvl=info msg="Live Push Gateway initialization" logger=live.push_http
t=2021-07-30T13:27:35+0700 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2021-07-30T13:27:37+0700 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=192.168.99.99 time_ms=1 size=0 referer=
t=2021-07-30T13:27:37+0700 lvl=info msg="Initialized channel handler" logger=live channel=grafana/dashboard/uid/nJM2QCWnk address=grafana/dashboard/uid/nJM2QCWnk
t=2021-07-30T13:27:38+0700 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=192.168.44.44 time_ms=1 size=0 referer=
t=2021-07-30T13:27:45+0700 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=400 remote_addr=192.168.99.99 time_ms=638 size=122406 referer="http://192.168.50.50:3000/d/nJM2QCWnk/dashboard-sankey?orgId=1&var-limit=5&var-dt=2020-10-03&var-exporter=All&var-description=All&var-sourceas=All&var-start=0&var-end=3000&editPanel=2"
`

**Comment by kumaravel29** [comment]
@mentaripagiku GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS is an environment variable, so it should not be part of grafana.ini
Also did you update the index.html with the script tag? - https://github.com/kumaravel29/grafana-sankey-panel#info

**Comment by tilmaehn** [comment]
@mentaripagiku If you want to keep the setting, you can set it in grafana.ini as follows: 
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/51676865/127622263-dce9b8c7-5772-4f7b-b594-fee00e58d000.png">

@kumaravel29 Thank you! Everything worked out.

**Comment by kumaravel29** [comment]
Updated the README.md with the adjustment for v8 Grafana
