### ISSUE TITLE
Support Grafana 7.X and 8.X

### ISSUE THREAD

**Issue by koctodox** [kumaravel29/grafana-sankey-panel#46]
Hi, Could you please update this plugin to support Grafana 7.X or 8.X

**Comment by kumaravel29** [comment]
@koctodox the plugin works with Grafana 7.x and 8.x

**Comment by koctodox** [comment]
> @koctodox the plugin works with Grafana 7.x and 8.x

I could not set up it. I use docker for Grafana
so I try to create my custom image [(here)](https://grafana.com/docs/grafana/latest/installation/docker/#build-and-run-a-docker-image-with-pre-installed-plugins) and try to past the <script> line (<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>) in inidex.html but no index.html I found so I copy the script line to index_template.html then build my image by adding your plugin repo URL as an environment variables like this:

`
docker run -d \
 -p 3001:3000 \ 
--name my_grafana  \
-e "GF_INSTALL_PLUGINS=https://github.com/kumaravel29/grafana-sankey-panel/archive/refs/heads/master.zip" \
-e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-sankey-panel"
my_image
`

but in the end, Grafana has a loading dashboard error and no Sankey represents to me at all.
I could not understand .what is my problem. I could not see any log. so I guess it's for my Grafana version (8.1).
would you help me to create a current docker image with Sankey panel ?

**Comment by kumaravel29** [comment]
@koctodox did you get it working or still facing issue?
