### ISSUE TITLE
Can InfluxDB be used as data source for Sankey-panel

### ISSUE THREAD

**Issue by joriws** [kumaravel29/grafana-sankey-panel#5]
This is more like help wanted type of query. Sankey panel is loading and I can set up Metrics via wizard. But my problem is to get values in correct form from InfluxDB that Sankey-panel would show something else than undefined - NaN in legend.

So help is wanted in what form data needs to be queried.

**Comment by joriws** [comment]
With piechart and exactly the same query to same data I get a graph..

**Comment by kumaravel29** [comment]
In this sankey diagram implementation you need to have 2 grouping for the visual to load.
Can you send the query that you are trying and the piechart output(screenshot) to verify if thats possible.

**Comment by lephisto** [comment]
I have the same Issue, with two groupings. Data simply won't load. If I take the query from the Query Inspector and put it in influx cli, i get data returned..

**Comment by kumaravel29** [comment]
Hi @lephisto ,
Thanks for trying out Sankey Panel and sharing your findings.

The whole idea Sankey started with converting the PieChart representation to a flow type visual approach for multilevel group of objects and its more related to the sub grouping of the data. I have tested the working with Elasticsearch where the aggregations having sub groups(2 grouping condition).

I tried testing with InfluxDB and it seems to be grouping of tags or fields(only 1 level).
I doubt if you requirement would work with this panel.

**Comment by lephisto** [comment]
@kumaravel29  So did your Influx Test work for you? Can you send a Testdataset then, so I can Model the data accordingly?

**Comment by kumaravel29** [comment]
No that did not work for me also because of single level of grouping.

**Comment by lephisto** [comment]
I think it would work if you could reference more then one Metric.

**Comment by shidaying** [comment]
my datasource is bigquery, it canot show anything
