### ISSUE TITLE
Using this panel with MSSQL

### ISSUE THREAD

**Issue by gs9824** [kumaravel29/grafana-sankey-panel#6]
Hello, 

Great that this exists for Grafana :)

I would like to use this panel using MSSQL query as datasource 

The data is organised as follows 
starttime;origin;destination;countthem
t1;A;B;20
t1;A;C;10
t1,B;A;30
t1;B;C;40
t1;C;A;10
t1;C;B;30

The query would look something like this :

SELECT
  $__timeGroup(starttime, '1h') AS time,
  SUM(CAST(CountThem AS NUMERIC)) AS value,
  origin, destination
FROM
  mytable
GROUP BY
  origin,destination,$__timeGroup(starttime, '1h')

I have tried multiple queries (e.g. format as table & ommitting all time related stuff), but I can't seem to get the visual working ... 

What should the expected format of the data that the query has to return ?

**Comment by gs9824** [comment]
SELECT
  origin, destination,
  SUM(CountThem) as value
FROM
  mytable
GROUP BY
  origin,destination

and Format as table 

gives cannot read property 'length' of undefined error

**Comment by kumaravel29** [comment]
I have not tested this plugin with MSSQL.
