### ISSUE TITLE
How to upgrade to be CloudWatch compatible? 

### ISSUE THREAD

**Issue by japbujan** [kumaravel29/grafana-sankey-panel#8]
Hi. 

We have CloudWatch as data source and its working well for most of the standard plugins. We are looking for a SanKey panel and this is fantastic for us, but it doesn't show anything in the panel. We can configure and work with the panel (no issues on console) but probably the plugin require some data structure and maybe cloudwatch is different. 

We want help and guidance to modify this plugin to adapt the plugin to a cloudwatch data source (we will publish the result in this GitHub for the community).

This is an example of query in our case.

Thanks in advance. 

Regards. 
<img width="1217" alt="screen shot 2018-11-14 at 15 21 03" src="https://user-images.githubusercontent.com/37404204/48488410-fca3f080-e820-11e8-9203-a8a71e91f14a.png">

**Comment by kumaravel29** [comment]
I have build the plugin based on the Elasticsearch datasource only where there is grouping of data based on keyword.
If it is possible for similar type of grouped data, then it can be visualized in Sankey.
Some sample data would be useful if need further assistance.

**Comment by kumaravel29** [comment]
Only support for Elasticsearch datasource for now
